'use client';

import { Stack, Title, Text, Alert, Group, Button, Paper, Divider } from '@mantine/core';
import { IconInfoCircle, IconFlask } from '@tabler/icons-react';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { notifications } from '@mantine/notifications';
import { Input } from '@/components/ui/input';
import { SelectDropdown } from '@/components/ui/select-dropdown';
import { Textarea } from '@/components/ui/textarea';

/**
 * Create a new BOM / Formula for a NEW product line.
 * The product name is a free-text input — it creates a new product entry
 * alongside the BOM. Existing formulas are managed from the BOM list.
 */

export default function CreateBOMPage() {
  const router = useRouter();
  const [saving, setSaving] = useState(false);

  const [form, setForm] = useState({
    product_name: '',
    product_code: '',
    product_unit: 'pcs',
    version: '1',
    is_active: true,
    notes: '',
  });

  const handleSave = async () => {
    const errors: string[] = [];
    if (!form.product_name.trim()) errors.push('Product name is required');
    if (!form.product_code.trim()) errors.push('Product code is required');
    if (!form.version.trim()) errors.push('Version is required');

    if (errors.length > 0) {
      notifications.show({ title: 'Validation', message: errors.join('. '), color: 'red' });
      return;
    }

    setSaving(true);
    try {
      // Step 1: Create the new product
      const productRes = await fetch('/api/items/products', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: form.product_name.trim(),
          code: form.product_code.trim().toUpperCase(),
          unit: form.product_unit,
          status: 'active',
        }),
      });
      if (!productRes.ok) {
        const err = await productRes.json();
        throw new Error(err?.errors?.[0]?.message ?? 'Failed to create product');
      }
      const productData = await productRes.json();
      const newProductId = productData?.data?.id;
      if (!newProductId) throw new Error('Product created but ID not returned');

      // Step 2: Create the BOM linked to the new product
      // Name is auto-generated by the backend extension: "{product_name} - Formula v{version}"
      const bomRes = await fetch('/api/items/boms', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          product_id: newProductId,
          version: form.version.trim(),
          is_active: form.is_active,
          notes: form.notes || null,
        }),
      });
      if (!bomRes.ok) {
        const err = await bomRes.json();
        throw new Error(err?.errors?.[0]?.message ?? 'Failed to create formula');
      }
      const bomData = await bomRes.json();
      notifications.show({ title: 'Created', message: `Formula for "${form.product_name}" created successfully`, color: 'green' });
      router.push(`/ppic/bom/${bomData?.data?.id ?? ''}`);
    } catch (err) {
      notifications.show({ title: 'Error', message: err instanceof Error ? err.message : 'Failed', color: 'red' });
    } finally {
      setSaving(false);
    }
  };

  return (
    <Stack gap="md">
      <div>
        <Title order={2}>Create New Formula</Title>
        <Text c="dimmed" size="sm">
          Add a formula for a new product line. This creates both the product entry and its formula.
        </Text>
      </div>

      <Alert icon={<IconInfoCircle size={16} />} color="blue" variant="light">
        This form is for <strong>new product lines</strong>. To edit an existing formula (e.g. Sigma Rose EDP, Sigma Oud EDT), go back to the BOM list and click the formula directly.
      </Alert>

      <Paper p="md" radius="md" withBorder>
        <Stack gap="sm">
          <Text size="sm" fw={600} c="dimmed" tt="uppercase">New Product Details</Text>

          <Group grow align="flex-start">
            <Input
              label="Product Name *"
              placeholder="e.g. Sigma Jasmine EDP 30ml"
              value={form.product_name}
              onChange={(v) => setForm((f) => ({ ...f, product_name: String(v ?? '') }))}
              required
            />
            <Input
              label="Product Code *"
              placeholder="e.g. EDP-006"
              value={form.product_code}
              onChange={(v) => setForm((f) => ({ ...f, product_code: String(v ?? '') }))}
              required
            />
          </Group>

          <Group grow align="flex-start">
            <SelectDropdown
              label="Unit *"
              choices={[
                { text: 'pcs', value: 'pcs' },
                { text: 'kg', value: 'kg' },
                { text: 'liter', value: 'liter' },
                { text: 'bottle', value: 'bottle' },
              ]}
              value={form.product_unit}
              onChange={(v) => setForm((f) => ({ ...f, product_unit: String(v ?? 'pcs') }))}
            />
            <Input
              label="Formula Version *"
              placeholder="e.g. 1"
              value={form.version}
              onChange={(v) => setForm((f) => ({ ...f, version: String(v ?? '') }))}
              required
            />
          </Group>

          <Divider label="Formula Settings" labelPosition="left" />

          <SelectDropdown
            label="Set as Active Formula"
            choices={[
              { text: 'Yes — this is the active formula', value: 'true' },
              { text: 'No — save as inactive/draft', value: 'false' },
            ]}
            value={form.is_active ? 'true' : 'false'}
            onChange={(v) => setForm((f) => ({ ...f, is_active: v === 'true' }))}
          />

          <Textarea
            label="Notes"
            placeholder="Formula notes (optional)..."
            value={form.notes}
            onChange={(v) => setForm((f) => ({ ...f, notes: String(v ?? '') }))}
          />
        </Stack>
      </Paper>

      <Group justify="flex-end">
        <Button variant="subtle" onClick={() => router.push('/ppic/bom')}>Cancel</Button>
        <Button leftSection={<IconFlask size={16} />} onClick={handleSave} loading={saving}>
          Create Product &amp; Formula
        </Button>
      </Group>
    </Stack>
  );
}
